#ifndef CHUDNOVSKY_SNAKE_LIKE_WITH_SIMPLIFIED_EXPRESSION_GMP
#define CHUDNOVSKY_SNAKE_LIKE_WITH_SIMPLIFIED_EXPRESSION_GMP

void chudnovsky_snake_like_with_simplified_expression_algorithm_gmp(mpf_t, int, int);

#endif

