#ifndef GMP_CHUDNOVSKY_SIMPLIFIED_EXPRESSION_INTEGERS_BLOCKS
#define GMP_CHUDNOVSKY_SIMPLIFIED_EXPRESSION_INTEGERS_BLOCKS

void gmp_chudnovsky_simplified_expression_integers_blocks_algorithm(mpf_t, int, int);

#endif

