#ifndef CHUDNOVSKY_CHEATER_WITH_SIMPLIFIED_EXPRESSION_GMP
#define CHUDNOVSKY_CHEATER_WITH_SIMPLIFIED_EXPRESSION_GMP

void chudnovsky_cheater_with_simplified_expression_algorithm_gmp(mpf_t, int, int);

#endif

